### ISSUE TITLE
FPS Drops and Freezing After 2 Hours - Possible Plugin Issue

### ISSUE THREAD

**Issue by itsarde** [qt31415926535-femboy/custom-vital-bars#3]
I've noticed that after playing RuneLite for about 2 hours, I start experiencing FPS drops and stuttering, which eventually lead to the game completely freezing. I've found that restarting RuneLite temporarily fixes the issue, but it's frustrating to have to do this every couple of hours.

I've also tested disabling the problematic plugin, and this resolves the FPS drops and freezes. It seems like the plugin is the only factor causing these issues. First, the FPS starts dropping, then the lag gets worse until the game fully freezes.

I'd appreciate any advice or solutions to avoid needing constant restarts. Thanks!

**Comment by jiropurple** [comment]
I was having the same issue, but it's already been brought up [here](https://github.com/qt31415926535-femboy/custom-vital-bars/issues/2). So hopefully it's being worked on.

**Comment by itsarde** [comment]
lmk when issue has been fixed. disabling the plug-in for now.

**Comment by chloe6111** [comment]
Yes, this crashes after 2+ hours. Please fix, lost all my progress in a raid. Turning off the plugin when it starts freezing doesn't even help.

**Comment by qt31415926535-femboy** [comment]
> Yes, this crashes after 2+ hours. Please fix, lost all my progress in a raid. Turning off the plugin when it starts freezing doesn't even help.

this really sucks, I'm sorry to hear :( I've currently "fixed" the code insofar as I've written the code that should fix it but haven't had the chance to test it because something seems to be wrong with my updated Runelite codebase. that is to say, I can upload the new code now and see if that fixes things at least?

**Comment by Kedjik** [comment]
> Thanks so much for getting back to us, @qt31415926535-femboy . I’ve turned your plugin back on, but unfortunately, I'm still experiencing the same issue—it doesn't seem to be working just yet. If you could give it another try, I’d really appreciate it. I’d love to keep using your plugin because it’s fantastic. Thanks a lot!

They didnt push the update yet sadly. I cant wait for the fix too this plugin is really nice to have. 


> this really sucks, I'm sorry to hear :( I've currently "fixed" the code insofar as I've written the code that should fix it but haven't had the chance to test it because something seems to be wrong with my updated Runelite codebase. that is to say, I can upload the new code now and see if that fixes things at least?

I hope that fixes the crash issue. Will be there a disable prayer drain animation option in the next update? Its really distracting sadly since its not that smooth.

**Comment by qt31415926535-femboy** [comment]
I have good news, the code has been pushed and is awaiting merging to the main plugin hub codebase. so now it's just a matter of waiting.

> I hope that fixes the crash issue. Will be there a disable prayer drain animation option in the next update? Its really distracting sadly since its not that smooth.
next update will allow you to set the border size per-bar so that you can remove the border for Prayer
