### ISSUE TITLE
Few suggestions

### ISSUE THREAD

**Issue by Kedjik** [qt31415926535-femboy/custom-vital-bars#4]
Plugin seems to be working great after 1.1.0 update thanks for updating it. I have few suggestions tho.

- Option to disable the HP regen bar when the HP is full. (enable again when overhealed)
- Option to make the special bar glow when certain threshold is passed instead of when its lower than that threshold. (like a spec reminder) Should be an option tho since you might want to know if ur missing spec when sending toa with yellow keris.

**Comment by qt31415926535-femboy** [comment]
sorry for the long delay in replying, but these are great ideas and I have incorporated them into the next update in one form or another. thanks for the support!
